### ISSUE TITLE
Improve templating compiler

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#234]
I have a feeling that this will cause us pain: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js#L26-L27

I think that if we use two widgets on one screen, both requiring template compilation, that only one will work, because one overrides the other

**Comment by adriatic** [comment]
How is this KendoUI specific? Assume that the widgets (call them custom elements to stay within Aurelia domain) and each of them requires template compilation how would this be different?

Asking these questions only because my understanding of Aurelia is still at very basic level. 

Also, I am quite happy that you raised this issue now, instead of starting this conversation as a reaction to someone's bug report. 

If you were "constructed like I am", you would find that all such issues get best resolved by writing down the problem to the level of gory details. At that point several good things happen:

- you might suddenly see the solution yourself
- we can engage someone else into this issue without the need to first explain it
- we get a nice piece of documentation

**Comment by JeroenVinke** [comment]
If you want to use Aurelia's enhance feature, you need to have 3 things: the element, the context, and the parent context.

For example, in a datagrid, we have the `<tr>` as the element, `{ my-name: 'Jeroen' }` as the context, and `public class MyViewModelContainingAGrid {}` as the parent context. 

When Kendo asks us to compile a view, it provides us two things: the element and the context. The parent context however, is something we needed to get from somewhere else. We used to keep this parent context in the [templating-compiler](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js), but the templating-compiler is a singleton, which would give us problems in the future.

It turns out that when Kendo calls `angular` to compile a view, that it does this in the context of the widget. This means that we can store practically anything on the widget, and then pull it off when Kendo wants us to compile something. So, I put the parent context on there, and moved this piece of code into the widget base [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/widget-base.js#L99). Now when Kendo calls us to compile something, we get the element and context from Kendo, and retrieve the parent context from the Kendo widget.

Now, one important change is that we need to pass the parent context from each wrapper onto the widget base. You can get this parent context from the `bind` lifecycle event, so the widget base does that by default. But sometimes you also want to initialize the control from `bind`, which would require you to call `bind` on the widget base first https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/button/button.js#L17-L21.

**Comment by JeroenVinke** [comment]
added this check though: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/372d3319c15de1fb499187385010db13fb4534ee/src/common/widget-base.js#L82, so you'll know immediately when you forgot to call bind() on the widget base

**Comment by adriatic** [comment]
> the templating-compiler is a singleton, which would give us problems in the future.

Knowing this is more than half of the battle won. I am assuming that the invocation of the template compiler is synchronous, so that by keeping your complete context "outside" the compiler is all you need to do.

**Comment by JeroenVinke** [comment]
Correct

**Comment by adriatic** [comment]
Love [this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/372d3319c15de1fb499187385010db13fb4534ee/src/common/widget-base.js#L82)
